name: LunaPVP
version: '${project.version}'
main: me.luna.Main
api-version: 1.17
authors: [Luna]
commands:
  game:
    usage: "Usage: /game [subcommand]"
    description: Handles game commands only for OP
  class:
    usage: "Usage: /class [Ability]"
    description: Works for all players before game start