name: LunaPVP
version: '${project.version}'
main: me.luna.lunapvp.Main
api-version: 1.17
authors: [Luna]
commands:
  start:
    usage: "Usage: /start"
    description: Starts game only for OP
  pvp_ability:
    usage: "Usage: /pvp_ability [Ability]"
    description: Works for all players before game start
  pvp_team:
    usage: "Usage: /pvp_team [Team_Name]"
    description: Works for all players before game start