name: LunaPVP
version: '${project.version}'
main: me.luna.lunapvp.main
api-version: 1.17
authors: [Luna]
commands:
  start:
    usage: "Usage: /start"
    description: Starts game only for OP
  ability:
    usage: "Usage: /ability [Quirk]"
    description: Works for all players before game start