name: LunaPVP
version: '1.0'
main: me.luna.lunapvp.main
api-version: 1.17
authors: [Luna]
commands:
  start:
    usage: "Usage: /start"
    description: Starts game only for OP
  ability:
    usage: "Usage: /ability [Quirk]"
    description: Works for all players before game start
  team:
    usage: "Usage: /team [teamName]"
    description: Works for all players before game start